import re

input = """; generated by Slic3r 1.2.9 on 2016-06-15 at 21:18:07

M107
M104 S200 ; set temperature
G92 E0
G1 Z0.200 F7200.000
G1 X75.572 Y93.157 F7200.000
G1 E2.00000 F2400.00000
G1 X83.572 Y87.157 E2.08588 F1200.000
"""

def shift(input, x, y):
    # https://docs.python.org/2/library/re.html#re.sub
    input = re.sub('X([^\s]+)', lambda o: 'X' + str(float(o.group(1)) + x), input)
    input = re.sub('Y([^\s]+)', lambda o: 'Y' + str(float(o.group(1)) + y), input)
    return input

print(shift(input, 5.3, 4.87))